version: '3.8'

services:
  app:
    build: .
    ports:
      - '4001:4001'
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://haliltunc:123456@db:5432/sm_db?schema=public"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: haliltunc
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sm_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
